services:
  db:
    image: mariadb:11
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress123
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    #healthcheck:
      #test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p12345 || exit 1"]
      #interval: 10s
      #timeout: 5s
      #retries: 10
      #start_period: 60s


  
  wordpress:
    image: wordpress:6-apache
    container_name: wp
    #depends_on:
      #db:
        #condition: service_healthy
    ports:
      - "8082:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress123
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - wp_data:/var/www/html
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-login.php"]
      interval: 30s
      timeout: 10s
      retries: 5


volumes:
  db_data:
  wp_data:
